# Generated by Django 3.1.7 on 2021-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znackaReg', models.CharField(max_length=20)),
                ('typAuta', models.CharField(max_length=30)),
                ('pocetKM', models.IntegerField()),
                ('datumPoslSTK', models.DateField()),
            ],
        ),
    ]
