# Generated by Django 3.1.7 on 2021-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmenoPrijmeni', models.CharField(max_length=100)),
                ('cisloRidicaku', models.CharField(max_length=15)),
                ('datumNarozeni', models.DateField()),
            ],
        ),
    ]
