# Generated by Django 3.1.7 on 2021-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumCasZacatkuVypujcky', models.DateTimeField()),
                ('datumCasKonceVypujcky', models.DateTimeField()),
                ('cenaVypujcky', models.IntegerField()),
            ],
        ),
    ]
